version: "3.7"
services:
  flask_api:
    build:
      context: "."
      dockerfile: "./docker/flask/Dockerfile"
    container_name: "flask_api"
    ports:
      - "5000:5000"
    user: root
    env_file:
      - "ui/.env"
  react_app:
    build:
      context: "."
      dockerfile: "./docker/react/Dockerfile"
    container_name: "react_app"
    ports:
      - "3000:3000"
    depends_on:
      - flask_api
    env_file:
      - "ui/.env"
  nginx:
    build:
      context: "."
      dockerfile: "./docker/nginx/Dockerfile"
    restart: unless-stopped
    ports:
      - 80:80
    depends_on:
      - flask_api
      - react_app
