version: '3.7'
services:
  flask_app:
    build:
      context: '.'
      dockerfile: './docker/flask/Dockerfile'
    container_name: "flask_api"
    ports:
      - "5000:5000"
  panel_app:
    build:
      context: "."
      dockerfile: "./docker/panel/Dockerfile"
    container_name: "panel_app"
    ports:
      - "5006:5006"
